# Site settings
title: "Costs & Benefits"
header-img: img/Tidy6.jpg
email: jkingston@kingstoncarnegie.com
description: "A value investing blog"
baseurl: ""
url: "http://blog.kingstoncarnegie.com"
twitter_username: JAKingston
github_username:  Impensa
facebook_username:  josh.kingston.14
linkedin_username: joshkingston

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
future: true