# Site settings
title: "Costs & Benefits"
header-img: img/tidy6.jpg
email: jkingston@kingstoncarnegie.com
description: "A value investing blog"
baseurl: "/"
url: "blog.kingstoncarnegie.com"
twitter_username: SBootstrap
github_username:  Impensa
facebook_username:  josh.kingston.14

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
